spring.application.name=backend

# 1. Conexión usando las variables del .env
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de Hibernate (CAMBIADO A UPDATE)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Estrategia de nombrado (Muy importante para que nombre_usuario en SQL case con username en Java)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# 4. Logs para depuración
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG